POST http://localhost:5000/rides/complete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImRyaXZlciIsInZlcmlmaWVkIjoxLCJpYXQiOjE3NDMzMzQ3MTgsImV4cCI6MTc0MzMzODMxOH0.luJwU53amXA6S968wf3EA5xOXy_YYhW7hN4MOOyou9s
Content-Type: application/json

{
    "rideId": 16
}