const db = require('../db');

exports.getActiveRide = (req, res) => {
  const userId = req.user.id; // Assumes req.user is set by authentication middleware

  db.query(
    'SELECT * FROM rides WHERE rider_id = ? AND status IN ("requested", "accepted", "arrived", "in progress") LIMIT 1',
    [userId],
    (err, results) => {
      if (err) {
        console.error('Database error:', err.message);
        return res.status(500).json({ message: 'Database error' });
      }
      if (results.length === 0) {
        return res.json(null); // No active ride found
      }
      const ride = results[0];

      // Instead of constructing a new route from driver/pickup/destination,
      // use the precomputed route stored in the ride.
      // (Assuming your requestRide endpoint stores it as encoded_polyline.)
      if (ride.encoded_polyline) {
        // Use the precomputed GeoJSON route (generated by Google)
        ride.route = JSON.parse(ride.encoded_polyline);
      } else {
        console.error("Missing precomputed route in ride record.");
      }

      return res.json(ride);
    }
  );
};
